server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.101:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.0.101:8080
    alibaba:
      seata:
        tx-service-group: gmall_tx_group
  zipkin:
    base-url: http://192.168.0.101:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      rate: 1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/guli_cart?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.0.101
    port: 6379
feign:
  sentinel:
    enabled: true

