server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.101:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.0.101:8080
    alibaba:
      seata:
        tx-service-group: gmall_tx_group
  zipkin:
    base-url: http://192.168.0.101:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      rate: 1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/guli_cart?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.0.101
    port: 6379
  task:
    execution:
      thread-name-prefix: gmall-cart-
      pool:
        core-size: 100
        max-size: 500
        keep-alive: 60
        queue-capacity: 800
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
feign:
  sentinel:
    enabled: true
mybatis-plus: # mybatis-plus 配置
  global-config:
    db-config:
      id-type: auto # id 策略, 生产应该使用分布式 id. auto 数据库自增
jwt:
  pubKeyPath: E:\learn\rsa\rsa.pub
  cookieName: GMALL-TOKEN
  userKey: user-key
  expire: 864000


