server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.101:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.0.101:8080
    alibaba:
      seata:
        tx-service-group: gmall_tx_group
  zipkin:
    base-url: http://192.168.0.101:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      rate: 1
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true



